### ISSUE TITLE
转换mobi格式报错

### ISSUE THREAD

**Issue by Mr-BeanSir** [ystyle/kaf-cli#34]
小说下载链接：https://dl1.wenku8.com/down.php?type=txt&id=1

```
kaf-cli.exe -author 乱 -filename C:\Users\USER\Downloads\Book\1.txt -cover C:\Users\USER\Downloads\Book\1.jpg -tips=0
转换信息:
软件版本: v1.3.5
文件名:  C:\Users\USER\Downloads\Book\1.txt
书籍书名: 1
书籍作者: 乱
书籍封面: C:\Users\USER\Downloads\Book\1.jpg
书籍语言: zh
匹配条件: 自动匹配
卷匹配条件: ^第[0-9一二三四五六七八九十零〇百千两 ]+[卷部]
转换格式: all

正在读取txt文件...
读取文件耗时: 332.4224ms
匹配章节: 96

kindlegen:  C:\Users\USER\Desktop\a\kindlegen.exe
正在生成epub
正在生成电子书...
生成EPUB电子书耗时: 384.937ms

使用第三方库生成azw3, 不保证所有样式都能正常显示
正在生成azw3...
生成azw3电子书耗时: 38.8024ms
kindlegen:  C:\Users\USER\Desktop\a\kindlegen.exe

检测到Kindle格式转换器: C:\Users\USER\Desktop\a\kindlegen.exe，正在把书籍转换成Kindle格式...
转换mobi比较花时间, 大约耗时1-10分钟, 请等待...

*************************************************************
 Amazon kindlegen(Windows) V2.9 build 1029-0897292
 命令行电子书制作软件
 Copyright Amazon.com and its Affiliates 2014
*************************************************************

信息:I9018:选项：-donotaddsource：不会添加源文件
信息:I9006:选项：-c1：标准 DOC 压缩
信息(prcgen):I1047: 已添加的元数据dc:Title        "1"
信息(prcgen):I1047: 已添加的元数据dc:Creator      "乱"
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\cover.xhtml     行： 0000008
信息(prcgen):I1052: Kindle 支持封面图像，但不支持封面采用 HTML。因此，在内容中使用指定的封面图像并禁止采用 HTML 封面。     网址： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\cover.xhtml
信息(prcgen):I1002: 解析文件  0000096
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0001.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0002.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0003.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0004.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0005.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0006.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0007.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0008.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0009.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0010.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0011.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0012.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0013.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0014.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0015.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0016.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0017.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0018.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0019.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0020.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0021.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0022.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0023.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0024.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0025.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0026.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0027.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0028.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0029.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0030.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0031.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0032.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0033.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0034.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0035.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0036.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0037.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0038.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0039.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0040.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0041.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0042.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0043.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0044.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0045.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0046.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0047.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0048.xhtml     行： 0000008
警告(inputpreprocessor):W29008: 由于用法不当，不使用的标签为： </link>
      文件中： C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\xhtml\section0049.xhtml     行： 0000008
信息(prcgen):I1015: 创建 PRC 文件
信息(prcgen):I1006: 分析超链接
警告(prcgen):W14019: 封面太小：  C:\Users\USER\AppData\Local\Temp\mbp_7E7_7_16_0_13_3_346_6DC_3CF8_1\EPUB\images\1.jpg
信息(pagemap):I8000: 没有在本书中发现页面图像
信息(prcgen):I1045: 本书中使用 UNICODE 范围计算
信息(prcgen):I1046: 已发现的 UNICODE 范围：Basic Latin [20..7E]
信息(prcgen):I1046: 已发现的 UNICODE 范围：CJK Unified Ideographs [4E00..9FFF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Miscellaneous Symbols [2600..26FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：General Punctuation - Windows 1252 [2013..2014]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Halfwidth and Fullwidth Forms [FF00..FFEF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Chinese, Japanese, and Korean (CJK) Symbols and Punctuation [3000..303F]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Hiragana [3040..309F]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Latin-1 Supplement [A0..FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Katakana [30A0..30FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Small Form Variants [FE50..FE6F]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Geometric Shapes [25A0..25FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：General Punctuation - other than Windows 1252 [203B..206F]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Box Drawing [2500..257F]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Specials [FFF0..FFFD]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Enclosed Alphanumerics [2460..24FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Arrows [2190..21FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Basic Greek [370..3FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Mathematical Operators [2200..22FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Cyrillic [400..4FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：Spacing Modifier Letters [2B0..2FF]
信息(prcgen):I1046: 已发现的 UNICODE 范围：CJK Compatibility Forms [FE30..FE4F]
信息(prcgen):I1017: 创建 PRC 文件，记录数：  0002193
信息(prcgen):I1039: 最终统计 - 文本压缩为（原始大小的 %）：  56.91%
信息(prcgen):I1040: 文档标识符是： "1"
信息(prcgen):I1041: 文件格式版本是 V6
信息(prcgen):I1031: 保存 PRC 文件
信息(prcgen):I1033: 创建 PRC 出现警告！
信息(prcgen):I1016: 创建改进的 PRC 文件
信息(prcgen):I1007: 分析媒体链接
信息(prcgen):I1011: 写入媒体链接
信息(prcgen):I1009: 分析指导项
信息(prcgen):I1017: 创建 PRC 文件，记录数：  0002079
信息(prcgen):I1039: 最终统计 - 文本压缩为（原始大小的 %）：  60.30%
信息(prcgen):I1041: 文件格式版本是 V8
信息(prcgen):I1032: 成功创建 PRC
信息(prcgen):I15000:可交付标准Mobi文件大小约为：  0005073KB
信息(prcgen):I15001:  KF8 可交付文件大小约为：  0005123KB
信息(prcgen):I1037: 创建 Mobi 域名文件出现警告！
panic: exit status 1

goroutine 1 [running]:
github.com/ystyle/kaf-cli.converToMobi({0xc0015fccca, 0x6}, {0x10d7221, 0x2})
        /home/runner/work/kaf-cli/kaf-cli/tools.go:64 +0x274
github.com/ystyle/kaf-cli.(*Book).Convert(0xc0001482c0)
        /home/runner/work/kaf-cli/kaf-cli/convert.go:411 +0x318
main.main()
        /home/runner/work/kaf-cli/kaf-cli/cmd/cli.go:38 +0x2d2
```

**Comment by ystyle** [comment]
已经解决了
